site_name: JS-Board
theme:
  name: material
  favicon: jsb-24.png
  logo: jsb-24.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

extra_css:
  - extra.css

nav:
  - index.md
  - "Quick Start":
    - quick-start/index.md




  # - known-issues.md
  # - "Quick Start":
  #   - quick-start/index.md
  #   - quick-start/docker.md
  #   - quick-start/examples.md
  # - "Using FlexDash":
  #   - 'using-flexdash/index.md'
  #   - 'using-flexdash/core-concepts.md'
  #   - 'using-flexdash/grid-panel-layout.md'
  #   - 'using-flexdash/iframes.md'
  #   - 'using-flexdash/edit-mode.md'
  #   - 'using-flexdash/nr-subflows.md'
  #   - 'using-flexdash/array-widgets.md'
  #   - 'using-flexdash/colors.md'
  #   - 'using-flexdash/time-plots.md'
  # - "Developing Widgets":
  #   - 'developing-widgets/index.md'
  #   - 'developing-widgets/quick-start.md'
  #   - 'developing-widgets/imports.md'
  #   - 'developing-widgets/vue-primer.md'
  #   - 'developing-widgets/vue-extensions.md'
  #   - 'developing-widgets/vuetify-primer.md'
  #   - 'developing-widgets/communication.md'
  #   - 'developing-widgets/widget-config.md'
  #   - 'developing-widgets/npm-start.md'
  #   - 'developing-widgets/node-generator.md'
  #   - 'developing-widgets/background.md'

